game:
  title: Lucid Twins
gameplay:
  deltatdivident: 100
  clamptozero: 0.001
  gravity: -0.0004
  jumpforce: 0.1
  moveacceleration:
    ground: 1.5
    air: 0.2
  breakacceleration:
    ground: 0.05
    air: 0.05
  maxspeed: 2.5
gui:
  tiledimension: 24
  playerviewtileheight: 12
  playerviewtilewidth: 30
graphics:
  animations:
    animationpath: animations/
    player1run:
      path: dreamrunevensmaller48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1idle:
      path: dreamstand48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1jump:
      path: dreamjump48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2run:
      path: dreamrungirlevensmaller48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2idle:
      path: dreamstandgirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2jump:
      path: dreamjumpgirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27