game:
  title: Lucid Twins
gameplay:
  deltatdivident: 100
  clamptozero: 0.001
  gravity: -0.0005
  jumpforce: 0.1
  moveacceleration:
    ground: 0.5
    air: 0.2
  breakacceleration:
    ground: 0.05
    air: 0.05
  maxspeed: 0.5
gui:
  tiledimension: 16
  playerviewtileheight: 12
  playerviewtilewidth: 30
graphics:
  animations:
    animationpath: animations/
    player: dreamrunsmaller70x100.png