game:
  title: Lucid Twins
gameplay:
  deltatdivident: 100
  clamptozero: 0.001
  gravity: -0.981
  jumpforce: 4.2
  moveacceleration:
    ground: 0.6
    air: 0.2
  breakacceleration:
    ground: 1.5
    air: 0.5
  maxspeed: 2.0
  maxYspeed: 5.0
  maxXspeed: 5.0
  gumspeed: 3.0
  gumstucktime: 7000
  pushspeedmax: 0.5
  pushaccelerationfactor: 0.5  
debug:
  fps: false
gamerules:
  switch:
    timeTillNext: 23000
    timeVariation: 0.2
    alertPhaseDuration: 5000
  doors:
    playerMinBehindDistance: 20.0
    playerMinBehindTime: 10000
    doorDuration: 10000
  creatures:
    speed: 1
   
gui:
  tiledimension: 24
  playerviewtileheight: 14
  playerviewtilewidth: 42
  colors:
    tintr: 255
    tintg: 255
    tintb: 0
graphics:
  animations:
    animationpath: animations/
    doorShow:
      path: objects/doorappeartemp.png
      framewidth: 48
      frameheight: 72
      fps: 27
    doorStay:
      path: objects/doortemp.png
      framewidth: 48
      frameheight: 72
      fps: 27
    doorBlow:
      path: objects/doordisappeartemp.png
      framewidth: 48
      frameheight: 72
      fps: 27
    bubbleGumGirl:
      path: objects/gumballpink7x7.png
      framewidth: 7
      frameheight: 7
      fps: 27
    bubbleGumBoy:
      path: objects/gumballblue7x7.png
      framewidth: 7
      frameheight: 7
      fps: 27
    player1run:
      path: dreamrunevensmaller48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1runGun:
      path: dreamrungun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1idle:
      path: dreamstandanim48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1idleGun:
      path: dreamstandgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1jump:
      path: dreamjump48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1jumpGun:
      path: dreamjumpgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1shot:
      path: dreamfiregun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1win:
      path: dreamwin48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1lose:
      path: dreamlose48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1stuck:
      path: dreamstuck48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2run:
      path: dreamrungirlevensmaller48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2runGun:
      path: dreamrungirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2idle:
      path: dreamstandgirlanim48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2idleGun:
      path: dreamstandgirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2jump:
      path: dreamjumpgirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2jumpGun:
      path: dreamjumpgirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2shot:
      path: dreamfiregirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2win:
      path: dreamwingirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2lose:
      path: dreamlosegirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2stuck:
      path: dreamstuckgirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    goodSheep:
      path: creatures/sheep.png
      framewidth: 72
      frameheight: 72
      fps: 27
    badSheep:
      path: creatures/badsheep.png
      framewidth: 72
      frameheight: 72
      fps: 27
    goodSheepStanding:
      path: creatures/sheepstanding.png
      framewidth: 72
      frameheight: 72
      fps: 27
    goodSheepMoveMouth:
      path: creatures/sheepmovemouth.png
      framewidth: 72
      frameheight: 72
      fps: 27
    badSheepStanding:
      path: creatures/sheepstanding.png
      framewidth: 72
      frameheight: 72
      fps: 27
    badSheepMoveMouth:
      path: creatures/sheepmovemouth.png
      framewidth: 72
      frameheight: 72
      fps: 27
    dreamSwitch:
      path: objects/dreamswitch.png
      framewidth: 72
      frameheight: 24
      fps: 27
    dreamSwitchPushed:
      path: objects/dreamswitchpushed.png
      framewidth: 72
      frameheight: 72
      fps: 27
    dreamSwitchAlarm:
      path: objects/dreamswitchalarm.png
      framewidth: 72
      frameheight: 72
      fps: 27
    dreamSwitchInactive:
      path: objects/dreamswitchinactive.png
      framewidth: 72
      frameheight: 72
      fps: 27
    pushBox:
      path: objects/pushbox.png
      framewidth: 72
      frameheight: 72
      fps: 27
levels:
  level1: 
    good: levels/test_24.tmx
    bad: levels/test_24.tmx
  level2:
    good: levels/Level design lucid twins_V5_good.tmx
    bad: levels/Level design lucid twins_V5_bad.tmx