game:
  title: Lucid Twins
gameplay:
  deltatdivident: 100
  clamptozero: 0.001
  gravity: -0.0005
  jumpforce: 0.1
  moveacceleration:
    ground: 0.5
    air: 0.2
  breakacceleration:
    ground: 0.05
    air: 0.05
  maxspeed: 0.5
gui:
  tiledimension: 16
  playerviewtileheight: 12
  playerviewtilewidth: 30
graphics:
  animations:
    animationpath: animations/
    player1run:
      path: runboy.png
      framewidth: 69
      frameheight: 99
      fps: 27
    player1idle:
      path: standboy.png
      framewidth: 69
      frameheight: 99
      fps: 27
    player1jump:
      path: jumpboy.png
      framewidth: 69
      frameheight: 99
      fps: 27
    player2run:
      path: rungirl.png
      framewidth: 65
      frameheight: 97
      fps: 27
    player2idle:
      path: standgirl.png
      framewidth: 65
      frameheight: 97
      fps: 27
    player2jump:
      path: jumpgirl.png
      framewidth: 65
      frameheight: 97
      fps: 27