game:
  title: Lucid Twins
gameplay:
  deltatdivident: 100
  clamptozero: 0.001
  gravity: -0.0004
  jumpforce: 0.1
  moveacceleration:
    ground: 1.5
    air: 0.2
  breakacceleration:
    ground: 0.05
    air: 0.05
  maxspeed: 2.5
gamerules:
  switch:
    timeTillNext: 7000
    timeVariation: 0.2
    alertPhaseDuration: 2000
  doors:
    playerMinDistance: 0.2
    doorDuration: 3000
   
gui:
  tiledimension: 24
  playerviewtileheight: 14
  playerviewtilewidth: 42
graphics:
  animations:
    animationpath: animations/
    player1run:
      path: dreamrunevensmaller48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1runGun:
      path: dreamrungun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1idle:
      path: dreamstand48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1idleGun:
      path: dreamstandgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1jump:
      path: dreamjump48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1jumpGun:
      path: dreamjumpgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player1shot:
      path: dreamfiregun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2run:
      path: dreamrungirlevensmaller48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2runGun:
      path: dreamrungirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2idle:
      path: dreamstandgirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2idleGun:
      path: dreamstandgirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2jump:
      path: dreamjumpgirl48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2jumpGun:
      path: dreamjumpgirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27
    player2shot:
      path: dreamfiregirlgun48x72.png
      framewidth: 48
      frameheight: 72
      fps: 27